trigger:
- master

variables:
  TOXENV: standard
  PYTEST_ADDOPTS: --numprocesses 4
  BRANCH_NAME: $(Build.SourceBranch)

jobs:
  - job: linux
    pool:
      vmImage: ubuntu-18.04
    strategy:
      matrix:
        python-2.7:
          PYTHON_VERSION: 2.7
        python-3.5:
          PYTHON_VERSION: 3.5
        python-3.8-light:
          PYTHON_VERSION: 3.8
          TOXENV: light
        python-3.8-cover:
          PYTHON_VERSION: 3.8
          TOXENV: cover
        lint:
          PYTHON_VERSION: 3.8
          TOXENV: lint
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
        displayName: Enable the targeted python version
      - script: python -m pip install --upgrade pip tox
        displayName: Install required runtime dependencies
      - script: python -m tox
        displayName: Execute tests through tox
      - script: |
          python -m pip install coveralls
          coveralls
        condition: eq(variables['TOXENV'], 'cover')
        env:
          COVERALLS_SERVICE_NAME: azure-pipelines
          COVERALLS_REPO_TOKEN: $(coveralls_repo_token)
        displayName: Publish code coverage

  - job: windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        python-2.7:
          PYTHON_VERSION: 2.7
        python-3.5:
          PYTHON_VERSION: 3.5
        python-3.8:
          PYTHON_VERSION: 3.8
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
          addToPath: true
        displayName: Enable the targeted python version
      - script: python -m pip install --upgrade pip tox wheel virtualenv setuptools
        displayName: Install required runtime dependencies
      - script: python -m tox
        displayName: Execute tests through tox
